engines:
  eslint:
    enabled: true
    config: "src/.eslintrc.json"
    channel: "eslint-3"
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - src/**
  - test/**
  - "**.js"
exclude_paths:
- test/**/*
- dist/**/*
- docs/**/*
- node_modules/**/*
